-- Create PR_GENERATIONS table for tracking Cortex-generated PRs
-- Run this in Snowflake console after setting up the BUGREWIND database

USE DATABASE BUGREWIND;
USE SCHEMA GIT_ANALYSIS;
USE WAREHOUSE BUGREWIND_WH;

-- PR Generations table (tracks all PR content generated by Cortex)
CREATE TABLE IF NOT EXISTS PR_GENERATIONS (
    GENERATION_ID VARCHAR(36) PRIMARY KEY,
    REPO_NAME VARCHAR(500) NOT NULL,
    FEATURE_REQUEST TEXT NOT NULL,
    IMPACTED_FILES ARRAY,
    IS_NEW_FEATURE BOOLEAN DEFAULT FALSE,
    PR_TITLE VARCHAR(500),
    BRANCH_NAME VARCHAR(500),
    GENERATED_BY_MODEL VARCHAR(100),
    EXECUTION_TIME_MS INTEGER,
    GENERATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    -- Index for common queries
    INDEX idx_repo_time (REPO_NAME, GENERATED_AT),
    INDEX idx_model (GENERATED_BY_MODEL)
);

-- Add some sample data for demo
INSERT INTO PR_GENERATIONS VALUES
(
    'demo-gen-001',
    'demo/youareabsolutelyright',
    'fix mobile login responsive design',
    PARSE_JSON('["src/pages/Login.tsx", "src/styles/login.css"]'),
    FALSE,
    'fix: Mobile login responsive design',
    'pm-copilot/fix-mobile-login-20251026-abc123',
    'cortex-mistral-large',
    2340,
    CURRENT_TIMESTAMP()
);

-- Verify table created
SELECT * FROM PR_GENERATIONS LIMIT 5;

-- Grant access
GRANT SELECT, INSERT ON TABLE PR_GENERATIONS TO ROLE PUBLIC;
